### ISSUE TITLE
WordPress

### ISSUE THREAD

**Issue by ghost** [dominicus-75/htaccess#1]
Üdvözöllek!

Ez kompatibilis lehet WordPressel is?

Köszönöm,
Lacesz

**Comment by dominicus75** [comment]
Üdv Lacesz!

Töredelmesen bevallom, még sohasem csináltam WP oldalt (tudtommal a WP-nek
van saját .htaccess állománya), így gőzöm sincs, hogy működnek-e együtt. A
.htaccess amúgy is csak Apache szerveren használható (ha nem ilyened van,
akkor sokra nem mész vele). Az állományból a káros robotok feketelistáját
nyugodtan el lehet hagyni, mivel elég régi (azóta gondolom fabrikáltak
millió újat, ami nincs a listán), e helyett célszerűbb egy fehér listát
beszúrni (azokat a robotokat felsorolva, amelyeknek engedélyezed a
hozzáférést, ez némiképp rövidebb lesz).

A puding próbája az elfogyasztás: XAMPP-on ki lehet próbálni, hogy a WP mit
szól hozzá ha a saját .htaccess-ét erre cseréled.

Üdv: Domi

thelacesz ***@***.***> ezt írta (időpont: 2021. ápr. 11., V,
15:28):

**Comment by dominicus75** [comment]
Domokos Endre János ***@***.***> ezt írta (időpont: 2021.
ápr. 12., H, 16:42):
